apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml

images:
  - name: ghcr.io/kylejwatson/mdns-operator
    newName: ghcr.io/kylejwatson/mdns-operator
    newTag: sha-346a6de
